### ISSUE TITLE
Can't send tokens to contract

### ISSUE THREAD

**Issue by jonathanjm** [blockxlabs/aiwa#3]
`const methodData = this.getContractInstance(TokenContract.address).send.getData(Contract.address,value,userData);
const tx = {to: TokenContract.address,data: methodData, value:value};
window.aionweb3.eth.sendTransaction(tx).then((res) => {
    //do something
}).catch((e) =>{
    console.log(e)
});`

When I execute this, Aiwa pops up and when I click 'Send', it returns 'The user cancelled sending transaction'

**Comment by jonpurdy-blockxlabs** [comment]
This has been fixed in 0.1.2.

**Comment by hamzahayat** [comment]
@jonathanjm And this was with the updated Token contract?

**Comment by jonathanjm** [comment]
Yup

**Comment by hamzahayat** [comment]
I believe that the issue still might lie within the contract itself though! I've sent you a message on gitter, could you please take a look!

**Comment by hamzahayat** [comment]
The reason that I believe it's a contract issue, is because the transaction is going through and getting mined. So it's not an AIWA issue. Or the code you're using within your DApp.
